
project_id = "dlmnucgxnwcrtteurfgr"

[realtime]
enabled = true
[realtime.tables]
public_projects = { table = "projects", schema = "public" }
public_profiles = { table = "profiles", schema = "public" }
public_blog_posts = { table = "blog_posts", schema = "public" }

[app_settings]
show_lovable_badge = false
