
project_id = "dlmnucgxnwcrtteurfgr"

[realtime]
enabled = true
[realtime.tables]
public_projects = { table = "projects", schema = "public" }
public_profiles = { table = "profiles", schema = "public" }

