// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlmnucgxnwcrtteurfgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsbW51Y2d4bndjcnR0ZXVyZmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MTE1MTQsImV4cCI6MjA1NjI4NzUxNH0.ApU-pZbTxbsA8dKyyg2Cxhz_3yy1dkz-2BN2k1-Z3ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);